const API='https://tgcmevhuxwzcmeseysax.supabase.co/functions/v1/bbq-customer-api';
const tg=window.Telegram?.WebApp;if(tg){tg.ready();tg.expand()}
const initData=tg?.initData||'';
let D={categories:[],products:[],banners:[],settings:{},user:null,profile:null,orders:[],orderStats:null},cart={},activeCat='all',checkoutAddressId=null,addressCoords=null,addressReturn='profile',heroIndex=0,heroTimer=null;
const $=s=>document.querySelector(s),money=n=>Number(n||0).toLocaleString('ru-RU')+' so‘m',esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
const statusNames={new:'🆕 Yangi',accepted:'✅ Qabul qilindi',preparing:'👨‍🍳 Tayyorlanmoqda',courier:'🛵 Kuryerda',delivered:'✅ Yetkazildi',cancelled:'❌ Bekor qilindi'};
async function call(action,extra={}){const r=await fetch(API,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,initData,...extra})});return r.json()}
async function start(){if(!initData){$('#status').textContent='Bu Mini App faqat Telegram bot ichidan ochiladi.';return}const r=await call('bootstrap');if(!r.ok){$('#status').textContent='Kirish xatosi: '+r.error;return}D={...D,...r};$('#status').classList.add('hide');syncHeader();renderHero();renderFeatured();renderCats();loadCart();renderProfile()}
function syncHeader(){$('#hello').textContent='Salom, '+(D.profile?.name||D.user?.first_name||'mijoz')+'!';$('#shopState').innerHTML=D.settings.shop_open===false?'<span class="pill">Yopiq</span>':'<span class="pill" style="background:#e5f8eb;color:#16743b">Ochiq</span>'}
function renderHero(){const arr=D.banners?.length?D.banners:[{title:'Issiq burger. Tez yetkazib berish.',subtitle:'Sevimli taomingizni bir necha bosishda buyurtma qiling.',image_url:null}];heroIndex=Math.min(heroIndex,arr.length-1);const b=arr[heroIndex],media=b.image_url?`<img src="${esc(b.image_url)}">`:'<div class="heroEmoji">🍔</div>',dots=arr.length>1?`<div class="heroDots">${arr.map((_,i)=>`<span class="heroDot ${i===heroIndex?'active':''}"></span>`).join('')}</div>`:'';$('#hero').innerHTML=`<div class="heroInner"><div class="heroText"><div class="heroEyebrow">🔥 BUGUNGI TAKLIF</div><h2>${esc(b.title||'BBQ Burger')}</h2><p>${esc(b.subtitle||'Issiq va mazali taomlar')}</p></div><div class="heroMedia">${media}</div></div>${dots}`;if(heroTimer)clearInterval(heroTimer);if(arr.length>1)heroTimer=setInterval(()=>{heroIndex=(heroIndex+1)%arr.length;renderHero()},5200)}
function featuredProduct(){return D.products.find(p=>p.is_in_stock&&/top|ko['‘’]?p|hit|best/i.test(String(p.badge||'')))||D.products.find(p=>p.is_in_stock)||null}
function renderFeatured(){const p=featuredProduct(),el=$('#featured');if(!p){el.classList.add('hide');return}el.classList.remove('hide');const media=p.image_url?`<img src="${esc(p.image_url)}">`:'<div class="featuredEmoji">🍔</div>';el.innerHTML=`<div class="featuredMedia">${media}</div><div class="featuredText"><div class="featuredTag">🔥 BUGUNGI HIT</div><div class="featuredName">${esc(p.name)}</div><div class="featuredPrice">${money(p.price_uzs)}</div><button class="featuredBtn" onclick="openProduct('${p.id}')">Ko‘rish</button></div>`}
function renderCats(){$('#cats').innerHTML=`<button class="cat active" data-id="all">🔥 Hammasi</button>`+D.categories.map(c=>`<button class="cat" data-id="${c.id}">${esc(c.emoji||'🍽️')} ${esc(c.name)}</button>`).join('');document.querySelectorAll('.cat').forEach(b=>b.onclick=()=>{document.querySelectorAll('.cat').forEach(x=>x.classList.remove('active'));b.classList.add('active');activeCat=b.dataset.id;renderProducts()})}
function filtered(){const q=$('#search').value.trim().toLowerCase();return D.products.filter(p=>(activeCat==='all'||p.category_id===activeCat)&&(!q||p.name.toLowerCase().includes(q)||(p.description||'').toLowerCase().includes(q)))}
function badgeText(p){const b=String(p.badge||'').trim();if(!b)return'';const l=b.toLowerCase();if(l.includes('top')||l.includes('ko‘p')||l.includes("ko'p"))return'🔥 '+b;if(l.includes('yangi'))return'✨ '+b;return b}
function renderProducts(){const arr=filtered();$('#productCount').textContent=arr.length+' ta mahsulot';$('#products').innerHTML=arr.map(p=>{const q=cart[p.id]||0;return `<article class="product" onclick="openProduct('${p.id}')"><div class="pic">${p.image_url?`<img src="${esc(p.image_url)}" alt="${esc(p.name)}">`:'🍔'}${p.badge?`<div class="badge">${esc(badgeText(p))}</div>`:''}${!p.is_in_stock?'<div class="sold">Hozir mavjud emas</div>':''}</div><div class="body"><div class="name">${esc(p.name)}</div><div class="desc">${esc(p.description||'Mazali va yangi tayyorlangan')}</div><div class="foot"><div class="price">${money(p.price_uzs)}</div>${p.is_in_stock?(q?`<div class="qty" onclick="event.stopPropagation()"><button onclick="chg('${p.id}',-1,event)">−</button><b>${q}</b><button onclick="chg('${p.id}',1,event)">+</button></div>`:`<button class="add" onclick="event.stopPropagation();chg('${p.id}',1,event)">+</button>`):''}</div></div></article>`}).join('')||'<div style="grid-column:1/3;text-align:center;padding:30px;color:#777">Mahsulot topilmadi</div>';updateBar()}
$('#search').oninput=renderProducts;
function categoryText(p){const c=D.categories.find(x=>x.id===p.category_id);return `${c?.slug||''} ${c?.name||''}`.toLowerCase()}
function isType(p,keys){const t=categoryText(p);return keys.some(k=>t.includes(k))}
function smartUpsells(max=3){const ids=new Set(Object.keys(cart)),hasMain=cartRows().some(x=>!isType(x.p,['ichimlik','sous','snack']));let pool=D.products.filter(p=>p.is_in_stock&&!ids.has(p.id));if(hasMain){pool.sort((a,b)=>{const score=p=>isType(p,['ichimlik'])?3:isType(p,['sous'])?2:isType(p,['snack'])?1:0;return score(b)-score(a)})}return pool.slice(0,max)}
function related(p,max=3){return D.products.filter(x=>x.is_in_stock&&x.id!==p.id).sort((a,b)=>(b.category_id===p.category_id?1:0)-(a.category_id===p.category_id?1:0)).slice(0,max)}
function recoHtml(list,title='Sizga yoqishi mumkin'){if(!list.length)return'';return `<div class="recoBlock"><div class="sectionTitle"><b>${title}</b></div><div class="recoScroll">${list.map(p=>`<div class="recoCard"><div class="recoPic">${p.image_url?`<img src="${esc(p.image_url)}">`:'🍔'}</div><div class="recoName">${esc(p.name)}</div><div class="recoPrice">${money(p.price_uzs)}</div><button class="recoAdd" onclick="chg('${p.id}',1,event)">+ Savatga</button></div>`).join('')}</div></div>`}
function flyToCart(id,ev){if(!ev?.currentTarget)return;const p=D.products.find(x=>x.id===id),from=ev.currentTarget.getBoundingClientRect(),to=$('#cartbar').getBoundingClientRect();const el=document.createElement(p?.image_url?'img':'div');el.className='fly';if(p?.image_url)el.src=p.image_url;else{el.textContent='🍔';el.style.display='flex';el.style.alignItems='center';el.style.justifyContent='center';el.style.fontSize='27px'}el.style.left=from.left+'px';el.style.top=from.top+'px';document.body.appendChild(el);requestAnimationFrame(()=>{el.style.left=(to.left+to.width*.68)+'px';el.style.top=(to.top+4)+'px';el.style.transform='scale(.45) rotate(18deg)';el.style.opacity='.2'});setTimeout(()=>el.remove(),600)}
function chg(id,d,ev){cart[id]=Math.max(0,(cart[id]||0)+d);if(!cart[id])delete cart[id];localStorage.setItem('bbq_cart',JSON.stringify(cart));if(d>0){flyToCart(id,ev);tg?.HapticFeedback?.impactOccurred('light')}renderProducts();const bar=$('#cartbar');bar.classList.remove('cartPulse');void bar.offsetWidth;bar.classList.add('cartPulse')}
function loadCart(){try{cart=JSON.parse(localStorage.getItem('bbq_cart')||'{}')||{}}catch{cart={}}renderProducts()}
function cartRows(){return Object.entries(cart).map(([id,q])=>({p:D.products.find(x=>x.id===id),q})).filter(x=>x.p)}
function totals(){const subtotal=cartRows().reduce((s,x)=>s+x.p.price_uzs*x.q,0),base=Number(D.settings.delivery_fee_uzs||0),threshold=Number(D.settings.free_delivery_threshold_uzs||0),fee=threshold>0&&subtotal>=threshold?0:base;return{subtotal,base,threshold,fee,total:subtotal+fee}}
function progressHtml(){const t=totals();if(!(t.threshold>0))return'';if(t.subtotal>=t.threshold)return `<div class="deliveryBox"><div class="deliveryTop"><span class="freeOk">🎁 Bepul yetkazib berish ochildi</span><span>0 so‘m</span></div><div class="progress"><div class="progressFill" style="width:100%"></div></div></div>`;const left=t.threshold-t.subtotal,p=Math.max(4,Math.min(96,t.subtotal/t.threshold*100));return `<div class="deliveryBox"><div class="deliveryTop"><span>🚚 Bepul dostavkagacha</span><span>${money(left)}</span></div><div class="progress"><div class="progressFill" style="width:${p}%"></div></div></div>`}
function smartBox(){const a=smartUpsells();if(!a.length)return'';return `<div class="smartBox"><div class="smartTitle">Birga yanada mazali</div><div class="smartSub">Buyurtmangizga mos qo‘shimchalar</div><div class="smartItems">${a.map(p=>`<div class="smartItem">${p.image_url?`<img src="${esc(p.image_url)}">`:'<div class="emoji">🥤</div>'}<b>${esc(p.name)}</b><button onclick="chg('${p.id}',1,event);openCart()">+ ${money(p.price_uzs)}</button></div>`).join('')}</div></div>`}
function updateBar(){const rows=cartRows(),n=rows.reduce((s,x)=>s+x.q,0),t=rows.reduce((s,x)=>s+x.p.price_uzs*x.q,0);$('#cartbar').style.display=n?'flex':'none';$('#cartCount').textContent=n+' ta';$('#cartTotal').textContent=money(t)}
function openProduct(id){const p=D.products.find(x=>x.id===id);if(!p)return;const q=cart[id]||0,media=p.image_url?`<img src="${esc(p.image_url)}">`:'<div class="detailEmoji">🍔</div>',control=!p.is_in_stock?'<button class="secondary" disabled>Hozir mavjud emas</button>':q?`<div class="qty"><button onclick="chg('${id}',-1,event);openProduct('${id}')">−</button><b>${q}</b><button onclick="chg('${id}',1,event);openProduct('${id}')">+</button></div>`:`<button class="detailAdd" onclick="chg('${id}',1,event);openProduct('${id}')">Savatga qo‘shish</button>`;$('#sheetContent').innerHTML=`<div class="detailMedia">${media}${p.badge?`<div class="detailBadge">${esc(badgeText(p))}</div>`:''}</div><div class="detailName">${esc(p.name)}</div><div class="detailDesc">${esc(p.description||'Mazali, yangi tayyorlangan va issiq holda yetkaziladi.')}</div><div class="detailFoot"><div class="detailPrice">${money(p.price_uzs)}</div>${control}</div>${recoHtml(related(p))}<button class="secondary" onclick="closeSheet()">Yopish</button>`;$('#sheet').style.display='flex'}
function openCart(){const rows=cartRows(),t=totals();$('#sheetContent').innerHTML=`<h2>Savat</h2>${rows.map(x=>`<div class="cartitem"><div><b>${esc(x.p.name)}</b><br><span class="hello">${money(x.p.price_uzs)} × ${x.q}</span></div><div class="qty"><button onclick="chg('${x.p.id}',-1,event);openCart()">−</button><b>${x.q}</b><button onclick="chg('${x.p.id}',1,event);openCart()">+</button></div></div>`).join('')}${progressHtml()}${smartBox()}<div class="sumrow"><span>Mahsulotlar</span><b>${money(t.subtotal)}</b></div><div class="sumrow"><span>Yetkazib berish</span><b>${t.fee===0&&t.threshold>0&&t.subtotal>=t.threshold?'BEPUL ✅':money(t.fee)}</b></div><div class="sumrow total"><span>Jami</span><span>${money(t.total)}</span></div><button class="primary" onclick="checkout()">Buyurtma berish</button><button class="secondary" onclick="closeSheet()">Davom etish</button>`;$('#sheet').style.display='flex'}
function closeSheet(){$('#sheet').style.display='none'}
function addressList(){return D.profile?.addresses||[]}
function checkout(){const p=D.profile||{},arr=addressList();if(!checkoutAddressId||!arr.some(a=>a.id===checkoutAddressId))checkoutAddressId=(arr.find(a=>a.is_default)||arr[0])?.id||null;const cards=arr.map(a=>`<button class="addressChoice ${a.id===checkoutAddressId?'selected':''}" data-address-id="${a.id}" onclick="selectCheckoutAddress('${a.id}')"><div class="choiceTop"><b>${esc(a.label)}</b>${a.is_default?'<span class="pill">Standart</span>':''}</div><div class="addrText">${esc(a.address_text||'Lokatsiya saqlangan')}</div></button>`).join('');$('#sheetContent').innerHTML=`<h2>Yetkazib berish</h2>${progressHtml()}<label>Ismingiz</label><input id="cname" value="${esc(p.name||'')}"><label>Telefon raqam</label><div class="verifyRow"><div><b>${esc(p.phone||'Tasdiqlanmagan')}</b><br><span class="${p.phone_verified?'ok':'bad'}">${p.phone_verified?'✅ Telegram orqali tasdiqlangan':'❌ Tasdiqlanmagan'}</span></div></div>${p.phone_verified?'':`<button class="verify" onclick="verifyPhone(true)">📱 Telegram orqali tasdiqlash</button>`}<div class="sectionHead" style="margin-top:14px"><b>Yetkazish manzili</b><button onclick="editAddress('', 'checkout')">+ Yangi</button></div>${cards||'<div class="info">Hali saqlangan manzil yo‘q. Avval manzil qo‘shing.</div>'}<label>Izoh</label><textarea id="comment" placeholder="Masalan: domofon ishlamaydi"></textarea>${arr.length?'<button class="primary" id="sendOrder" onclick="sendOrder()">Buyurtmani tasdiqlash</button>':''}<button class="secondary" onclick="openCart()">Orqaga</button>`;$('#sheet').style.display='flex'}
function selectCheckoutAddress(id){checkoutAddressId=id;document.querySelectorAll('.addressChoice').forEach(x=>x.classList.toggle('selected',x.dataset.addressId===id));tg?.HapticFeedback?.selectionChanged()}
async function sendOrder(){const btn=$('#sendOrder'),name=$('#cname').value.trim();if(!D.profile?.phone_verified){alert('Avval telefon raqamingizni Telegram orqali tasdiqlang');return}if(!name){alert('Ismingizni kiriting');return}if(!checkoutAddressId){alert('Yetkazish manzilini tanlang');return}btn.disabled=true;btn.textContent='Yuborilmoqda...';const save=await call('update_profile',{name});if(!save.ok){alert('Profilni saqlashda xato: '+save.error);btn.disabled=false;btn.textContent='Buyurtmani tasdiqlash';return}D.profile=save.profile;const r=await call('create_order',{items:cartRows().map(x=>({product_id:x.p.id,quantity:x.q})),customer_name:name,address_id:checkoutAddressId,comment:$('#comment').value.trim()});if(!r.ok){alert(r.error);btn.disabled=false;btn.textContent='Buyurtmani tasdiqlash';return}cart={};D.orderStats=null;localStorage.removeItem('bbq_cart');renderProducts();syncHeader();$('#sheetContent').innerHTML=`<div class="success"><div class="big">✅</div><h2>Buyurtma qabul qilindi</h2><p>Buyurtma raqami: <b>#${r.order.order_number}</b></p><p>Jami: <b>${money(r.order.total_uzs)}</b></p><button class="primary" onclick="closeSheet();showView('orders')">Buyurtmani ko‘rish</button></div>`}
async function loadOrders(){const r=await call('my_orders');if(!r.ok){$('#orders').innerHTML='<div class="profileCard">Xatolik: '+esc(r.error)+'</div>';return}D.orders=r.orders||[];D.orderStats=r.stats||D.orderStats;$('#orders').innerHTML=D.orders.map(o=>{const items=o.order_items||[],count=items.reduce((s,x)=>s+Number(x.quantity||0),0),preview=items.slice(0,3).map(x=>`${esc(x.product_name)} × ${x.quantity}`).join(' · ')+(items.length>3?' · …':'');return `<div class="order"><div class="orderTop"><div><div class="orderNum">Buyurtma #${o.order_number}</div><div class="muted">${new Date(o.created_at).toLocaleString()}</div></div><span class="pill">${statusNames[o.status]||o.status}</span></div><div class="orderItemsPreview">${preview||'Mahsulotlar topilmadi'}</div><div class="orderBottom"><div><b>${money(o.total_uzs)}</b><br><span class="muted">${count} ta · ${esc(o.address_text||'Lokatsiya')}</span></div><button class="reorderBtn" onclick="reorderOrder('${o.id}')">🔁 Qayta buyurtma</button></div></div>`}).join('')||'<div class="profileCard">Hozircha buyurtmalar yo‘q.</div>'}
function reorderOrder(id){const o=D.orders.find(x=>x.id===id);if(!o)return;let added=0,skipped=0;for(const item of o.order_items||[]){const p=D.products.find(x=>x.id===item.product_id&&x.is_in_stock);if(!p){skipped++;continue}const qty=Math.max(1,Number(item.quantity||1));cart[p.id]=Math.min(20,(cart[p.id]||0)+qty);added++}if(!added){alert('Bu buyurtmadagi mahsulotlar hozir menyuda mavjud emas.');return}localStorage.setItem('bbq_cart',JSON.stringify(cart));renderProducts();tg?.HapticFeedback?.notificationOccurred('success');showView('menu');openCart();const msg=skipped?`Savatga qaytarildi. ${skipped} ta hozir mavjud bo‘lmagan mahsulot qo‘shilmadi. Narxlar joriy narxda hisoblanadi.`:'Buyurtma savatga qaytarildi. Narxlar joriy narxda hisoblanadi.';setTimeout(()=>{if(tg?.showAlert)tg.showAlert(msg);else alert(msg)},120)}
function renderProfile(){const p=D.profile||{},arr=addressList(),st=D.orderStats,cards=arr.map(a=>`<div class="addrCard ${a.is_default?'default':''}"><div class="addrHead"><div><div class="addrTitle">${esc(a.label)}</div><div class="addrText">${esc(a.address_text||'Lokatsiya saqlangan')}</div></div>${a.is_default?'<span class="pill">Standart</span>':''}</div><div class="addrActions"><button class="miniPrimary" onclick="editAddress('${a.id}','profile')">✏️ Tahrirlash</button>${a.is_default?'':`<button class="miniDefault" onclick="setDefaultAddressUI('${a.id}')">⭐ Standart</button>`}<button class="miniDanger" onclick="deleteAddressUI('${a.id}')">🗑 O‘chirish</button></div></div>`).join('');const statHtml=`<div class="profileStats"><div class="profileStat"><span>🧾 Jami buyurtma</span><b>${st?Number(st.total_orders||0):'—'}</b></div><div class="profileStat"><span>💰 Jami xarid</span><b>${st?money(st.total_spent_uzs||0):'—'}</b></div><div class="profileStat"><span>✅ Yetkazilgan</span><b>${st?Number(st.delivered_orders||0):'—'}</b></div></div>`;$('#profileContent').innerHTML=`${statHtml}<div class="profileCard"><label>Ism</label><input id="pname" value="${esc(p.name||'')}"><button class="primary" onclick="saveProfileUI()">Ismni saqlash</button><label>Telefon</label><div class="verifyRow"><div><b>${esc(p.phone||'Raqam hali olinmagan')}</b><br><span class="${p.phone_verified?'ok':'bad'}">${p.phone_verified?'✅ Tasdiqlangan':'❌ Tasdiqlanmagan'}</span></div></div><button class="verify" id="verifyBtn" onclick="verifyPhone(false)">${p.phone_verified?'📱 Telefon raqamini o‘zgartirish':'📱 Telegram orqali telefonni tasdiqlash'}</button></div><div class="profileCard"><div class="sectionHead"><div><b>Saqlangan manzillar</b><div class="muted">Uy, Ish yoki boshqa manzil</div></div><button onclick="editAddress('','profile')">+ Qo‘shish</button></div>${cards||'<div class="info">Hali manzil saqlanmagan.</div>'}</div>`}
async function saveProfileUI(){const name=$('#pname').value.trim();if(!name){alert('Ismni kiriting');return}const r=await call('update_profile',{name});if(!r.ok){alert(r.error);return}D.profile=r.profile;syncHeader();renderProfile();alert('Ism saqlandi')}
async function refreshProfile(withStats=true){const r=await call('profile');if(!r.ok)return null;D.profile=r.profile;if(r.stats)D.orderStats=r.stats;if(withStats&&!r.stats){const h=await call('my_orders');if(h.ok){D.orders=h.orders||D.orders;D.orderStats=h.stats||D.orderStats}}syncHeader();renderProfile();return r.profile}
function editAddress(id='',returnTo='profile'){addressReturn=returnTo;const a=id?addressList().find(x=>x.id===id):null;addressCoords=(a?.latitude!=null&&a?.longitude!=null)?{latitude:a.latitude,longitude:a.longitude}:null;const label=a?.label||'Uy';$('#sheetContent').innerHTML=`<h2>${a?'Manzilni tahrirlash':'Yangi manzil'}</h2><label>Nomi</label><select id="addrLabel"><option ${label==='Uy'?'selected':''}>Uy</option><option ${label==='Ish'?'selected':''}>Ish</option><option ${label==='Boshqa'?'selected':''}>Boshqa</option></select><label>Manzil</label><input id="addrText" placeholder="Mahalla, ko‘cha, uy" value="${esc(a?.address_text||'')}"><button class="secondary" onclick="getAddressLocation()">📍 Lokatsiyani tanlash / yangilash</button><div class="locstate" id="addrLoc">${addressCoords?'✅ Lokatsiya saqlangan':'Lokatsiya tanlanmagan'}</div><div class="checkrow"><input id="addrDefault" type="checkbox" ${a?.is_default||!addressList().length||returnTo==='checkout'?'checked':''}><label for="addrDefault">Standart manzil qilish</label></div><button class="primary" onclick="saveAddressUI('${id}')">Saqlash</button><button class="secondary" onclick="${returnTo==='checkout'?'checkout()':'closeSheet()'}">Bekor qilish</button>`;$('#sheet').style.display='flex'}
function geo(setter,textId){if(!navigator.geolocation){$(textId).textContent='Bu qurilmada lokatsiya mavjud emas';return}$(textId).textContent='Joylashuv olinmoqda...';navigator.geolocation.getCurrentPosition(p=>{setter({latitude:p.coords.latitude,longitude:p.coords.longitude});$(textId).textContent='✅ Joylashuv olindi'},()=>{$(textId).textContent='Lokatsiya berilmadi. Manzilni qo‘lda yozing.'},{enableHighAccuracy:true,timeout:10000,maximumAge:30000})}
function getAddressLocation(){geo(v=>addressCoords=v,'#addrLoc')}
async function saveAddressUI(id){const label=$('#addrLabel').value,address=$('#addrText').value.trim(),isDefault=$('#addrDefault').checked;if(!address&&!addressCoords){alert('Manzil yozing yoki lokatsiyani tanlang');return}const r=await call('save_address',{id:id||undefined,label,address_text:address,latitude:addressCoords?.latitude??null,longitude:addressCoords?.longitude??null,is_default:isDefault});if(!r.ok){alert(r.error);return}D.profile=r.profile;const saved=id?D.profile.addresses.find(a=>a.id===id):D.profile.addresses.find(a=>a.label===label&&String(a.address_text||'')===address)||D.profile.address;if(addressReturn==='checkout'){checkoutAddressId=saved?.id||D.profile.address?.id||null;checkout()}else{closeSheet();renderProfile()}}
async function setDefaultAddressUI(id){const r=await call('set_default_address',{id});if(!r.ok){alert(r.error);return}D.profile=r.profile;renderProfile()}
async function deleteAddressUI(id){if(!confirm('Manzil o‘chirilsinmi?'))return;const r=await call('delete_address',{id});if(!r.ok){alert(r.error);return}D.profile=r.profile;if(checkoutAddressId===id)checkoutAddressId=D.profile.address?.id||null;renderProfile()}
async function verifyPhone(fromCheckout=false){if(!tg?.requestContact){tg?.showAlert?.('Bu Telegram versiyasida avtomatik telefon so‘rash mavjud emas. Bot chatiga /phone yuboring.');return}const btn=$('#verifyBtn');if(btn){btn.disabled=true;btn.textContent='Telegram tasdiqlashi kutilmoqda...'}tg.requestContact(async ok=>{if(!ok){if(btn){btn.disabled=false;btn.textContent='📱 Telegram orqali telefonni tasdiqlash'}return}for(let i=0;i<20;i++){await new Promise(r=>setTimeout(r,500));const p=await refreshProfile(false);if(p?.phone_verified){if(fromCheckout)checkout();return}}alert('Kontakt yuborildi, lekin tasdiqlash hali kelmadi.')})}
function showView(v){['menu','orders','profile'].forEach(x=>$('#'+x+'View').classList.toggle('hide',x!==v));document.querySelectorAll('.tabsBottom button').forEach(b=>b.classList.toggle('active',b.dataset.view===v));$('#cartbar').style.display=v==='menu'&&cartRows().length?'flex':'none';if(v==='orders')loadOrders();if(v==='profile')refreshProfile(true)}
document.querySelectorAll('.tabsBottom button').forEach(b=>b.onclick=()=>showView(b.dataset.view));$('#sheet').addEventListener('click',e=>{if(e.target.id==='sheet')closeSheet()});start();