(()=>{
let activePromo=null,promoNotice='';
const promoErrors={promo_required:'Promo-kodni kiriting',promo_not_found:'Bunday promo-kod topilmadi',promo_inactive:'Promo-kod hozir faol emas',promo_not_started:'Promo-kod hali boshlanmagan',promo_expired:'Promo-kod muddati tugagan',promo_min_order:'Buyurtma summasi promo uchun yetarli emas',promo_limit_reached:'Promo-kod limiti tugagan',promo_user_limit:'Siz bu promo-koddan foydalanib bo‘lgansiz',promo_invalid:'Promo-kod ishlamadi'};
const baseCall=call;
call=async function(action,extra={}){const payload={...extra};if(action==='create_order'&&activePromo?.code)payload.promo_code=activePromo.code;const r=await baseCall(action,payload);if(action==='create_order'&&r?.ok){activePromo=null;promoNotice=''}return r};
const baseTotals=totals;
totals=function(){const t=baseTotals(),d=activePromo&&activePromo.subtotal===t.subtotal?Math.min(Number(activePromo.discount_uzs||0),t.subtotal):0;return{...t,discount:d,total:Math.max(0,t.subtotal+t.fee-d)}};
function style(){if(document.querySelector('#promoAddonStyle'))return;const s=document.createElement('style');s.id='promoAddonStyle';s.textContent='.promoBox{background:#fff;border:1px dashed #ff9b55;border-radius:16px;padding:11px;margin:10px 0}.promoTitle{font-weight:950;font-size:13px}.promoRow{display:flex;gap:7px;margin-top:8px}.promoRow input{margin:0;flex:1;text-transform:uppercase}.promoRow button{border:0;border-radius:11px;background:#171717;color:#fff;font-weight:900;padding:0 13px}.promoOk{display:flex;align-items:center;justify-content:space-between;gap:8px;background:#eaf8ee;color:#16743b;border-radius:11px;padding:9px;margin-top:8px;font-size:12px;font-weight:900}.promoRemove{border:0;background:#fff;color:#c62828;border-radius:8px;padding:6px 8px}.promoHint{font-size:10.5px;color:#777;margin-top:5px}.discountRow{color:#16813c;font-weight:900}';document.head.appendChild(s)}
function promoHtml(){if(activePromo)return `<div class="promoBox"><div class="promoTitle">🎟 Promo-kod</div><div class="promoOk"><span>${esc(activePromo.code)} · −${money(activePromo.discount_uzs)}</span><button class="promoRemove" onclick="removePromoUI()">Olib tashlash</button></div></div>`;return `<div class="promoBox"><div class="promoTitle">🎟 Promo-kodingiz bormi?</div><div class="promoRow"><input id="promoInput" maxlength="30" placeholder="Masalan: BBQ10" value=""><button onclick="applyPromoUI()">Qo‘llash</button></div>${promoNotice?`<div class="promoHint">${esc(promoNotice)}</div>`:'<div class="promoHint">Chegirma mahsulotlar summasidan hisoblanadi.</div>'}</div>`}
function mountPromo(){style();const sc=document.querySelector('#sheetContent');if(!sc||!/^Savat$/i.test(sc.querySelector('h2')?.textContent||''))return;const old=sc.querySelector('.promoBox');if(old)old.remove();const firstSum=sc.querySelector('.sumrow');if(firstSum)firstSum.insertAdjacentHTML('beforebegin',promoHtml());if(activePromo){const total=sc.querySelector('.sumrow.total');if(total)total.insertAdjacentHTML('beforebegin',`<div class="sumrow discountRow"><span>🎟 Promo chegirma</span><b>−${money(activePromo.discount_uzs)}</b></div>`)} }
const baseOpenCart=openCart;
openCart=function(){baseOpenCart();mountPromo()};
window.applyPromoUI=async function(){const input=document.querySelector('#promoInput'),code=String(input?.value||'').trim().toUpperCase();if(!code){alert('Promo-kodni kiriting');return}const sub=baseTotals().subtotal;if(sub<=0){alert('Avval savatga mahsulot qo‘shing');return}const btn=input?.nextElementSibling;if(btn){btn.disabled=true;btn.textContent='...'}const r=await baseCall('promo_preview',{code,subtotal:sub});if(r.ok){activePromo={code:r.code,discount_uzs:Number(r.discount_uzs||0),subtotal:sub};promoNotice='';tg?.HapticFeedback?.notificationOccurred('success');openCart()}else{activePromo=null;promoNotice=promoErrors[r.error]||r.error||'Promo-kod ishlamadi';alert(promoNotice);mountPromo()}if(btn){btn.disabled=false;btn.textContent='Qo‘llash'}};
window.removePromoUI=function(){activePromo=null;promoNotice='';openCart()};
const baseChg=chg;
chg=function(id,d,ev){if(activePromo){activePromo=null;promoNotice='Savat o‘zgardi. Promo-kodni qayta qo‘llang.'}return baseChg(id,d,ev)};
const baseReorder=reorderOrder;
reorderOrder=function(id){activePromo=null;promoNotice='';return baseReorder(id)};
const baseLoadOrders=loadOrders;
loadOrders=async function(){await baseLoadOrders();const cards=document.querySelectorAll('#orders .order');cards.forEach((card,i)=>{const o=D.orders?.[i];if(o?.discount_uzs>0&&!card.querySelector('.promoOrderNote')){const note=document.createElement('div');note.className='orderItemsPreview promoOrderNote';note.innerHTML=`🎟 ${esc(o.promo_code||'Promo')} · chegirma <b>−${money(o.discount_uzs)}</b>`;card.querySelector('.orderBottom')?.before(note)}})};
style();
})();