(()=>{
const ANALYTICS_API='https://tgcmevhuxwzcmeseysax.supabase.co/functions/v1/bbq-analytics-api';
let analyticsPeriod='today',crmRows=[],analyticsMode=false,crmMode=false,crmTimer=null;
const acall=async(action,extra={})=>{const r=await fetch(ANALYTICS_API,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,initData,...extra})});return r.json()};
const pnames={today:'Bugun',week:'Hafta',month:'Oy'};
const sname={new:'🆕 Yangi',accepted:'✅ Qabul',preparing:'👨‍🍳 Tayyor',courier:'🛵 Kuryer',delivered:'✅ Yetkazildi',cancelled:'❌ Bekor'};
function addAnalyticsStyles(){if(document.querySelector('#analyticsStyle'))return;const s=document.createElement('style');s.id='analyticsStyle';s.textContent='.anaGrid{display:grid;grid-template-columns:1fr 1fr;gap:9px;margin:10px 0}.anaCard{background:#fff;border-radius:17px;padding:13px;box-shadow:0 3px 14px #0000000c}.anaValue{font-size:19px;font-weight:900;line-height:1.15}.anaLabel{font-size:11px;color:#777;margin-top:5px}.anaNote{background:#fff7eb;border-radius:14px;padding:10px 12px;font-size:11px;color:#6d563f;line-height:1.5}.anaSection{margin-top:14px}.anaRow{background:#fff;border-radius:15px;padding:11px 12px;margin:7px 0}.anaHead{display:flex;align-items:center;justify-content:space-between;gap:10px}.anaBar{height:7px;background:#eee;border-radius:999px;overflow:hidden;margin-top:7px}.anaFill{height:100%;background:#ff6500;border-radius:999px}.crmSearch{position:sticky;top:0;background:#f4f4f4;padding:4px 0 6px;z-index:2}.crmCard{background:#fff;border-radius:17px;padding:13px;margin:8px 0;box-shadow:0 3px 14px #0000000c}.crmStats{display:grid;grid-template-columns:repeat(3,1fr);gap:6px;margin-top:9px}.crmMini{background:#f7f7f7;border-radius:10px;padding:7px;text-align:center}.crmMini b{display:block;font-size:13px}.crmMini span{font-size:9px;color:#777}.crmMeta{font-size:11px;color:#777;line-height:1.5;margin-top:5px}.crmDetail{width:100%;margin-top:9px;background:#eef6ff;color:#1565c0}.periodFilters{display:flex;gap:6px;margin:9px 0}.periodFilters button{flex:1;background:#fff}.periodFilters button.active{background:#ff6500;color:#fff}';document.head.appendChild(s)}
function clearTabs(){document.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('active'))}
function fmtDate(v){if(!v)return'-';try{return new Date(v).toLocaleString('uz-UZ')}catch{return String(v)}}
function num(v){return Number(v||0).toLocaleString('ru-RU')}
async function renderAnalytics(){analyticsMode=true;crmMode=false;const c=document.querySelector('#content');if(!c)return;c.innerHTML='<div class="empty">Analitika yuklanmoqda...</div>';const r=await acall('dashboard',{period:analyticsPeriod}).catch(()=>null);if(!r?.ok){c.innerHTML='<div class="empty">Analitikani yuklab bo‘lmadi'+(r?.error?': '+esc(r.error):'')+'</div>';return}const x=r.summary||{},top=r.top_products||[],customers=r.top_customers||[],mx=Math.max(1,...top.map(z=>Number(z.quantity||0)));let h=`<div class="toolbar"><div><b>Analitika</b><div class="muted">Real buyurtmalar asosida</div></div><button onclick="renderAnalytics()">↻ Yangilash</button></div><div class="periodFilters">${['today','week','month'].map(p=>`<button class="${analyticsPeriod===p?'active':''}" onclick="setAnalyticsPeriod('${p}')">${pnames[p]}</button>`).join('')}</div><div class="anaNote">Savdo summasi faqat <b>Yetkazildi</b> statusidagi buyurtmalardan hisoblanadi. Bekor qilingan buyurtmalar savdoga qo‘shilmaydi.</div><div class="anaGrid"><div class="anaCard"><div class="anaValue">${money(x.sales_uzs||0)}</div><div class="anaLabel">Yetkazilgan savdo</div></div><div class="anaCard"><div class="anaValue">${num(x.delivered_orders)}</div><div class="anaLabel">Yetkazilgan buyurtma</div></div><div class="anaCard"><div class="anaValue">${money(x.average_check_uzs||0)}</div><div class="anaLabel">O‘rtacha chek</div></div><div class="anaCard"><div class="anaValue">${num(x.cancelled_orders)}</div><div class="anaLabel">Bekor qilingan</div></div><div class="anaCard"><div class="anaValue">${num(x.active_customers)}</div><div class="anaLabel">Faol mijoz</div></div><div class="anaCard"><div class="anaValue">${num(x.new_customers)}</div><div class="anaLabel">Yangi mijoz</div></div><div class="anaCard"><div class="anaValue">${num(x.repeat_customers)}</div><div class="anaLabel">Qayta buyurtma qilgan</div></div><div class="anaCard"><div class="anaValue">${money(x.discounts_uzs||0)}</div><div class="anaLabel">Berilgan chegirma</div></div></div>`;
h+=`<div class="anaSection"><div class="toolbar"><b>🏆 Eng ko‘p sotilgan mahsulotlar</b></div>${top.length?top.map((z,i)=>`<div class="anaRow"><div class="anaHead"><div><b>${i+1}. ${esc(z.product_name||'Mahsulot')}</b><div class="muted">${num(z.orders_count)} ta buyurtmada</div></div><div style="text-align:right"><b>${num(z.quantity)} dona</b><div class="muted">${money(z.gross_revenue_uzs||0)}</div></div></div><div class="anaBar"><div class="anaFill" style="width:${Math.max(4,Math.round(Number(z.quantity||0)/mx*100))}%"></div></div></div>`).join(''):'<div class="empty">Bu davrda yetkazilgan mahsulot yo‘q</div>'}</div>`;
h+=`<div class="anaSection"><div class="toolbar"><b>👑 TOP mijozlar</b><button onclick="openCrmTab()">Barchasi</button></div>${customers.length?customers.slice(0,5).map((u,i)=>`<div class="anaRow"><div class="anaHead"><div><b>${i+1}. ${esc(u.customer_name||'Noma’lum')}</b><div class="muted">${u.username?'@'+esc(u.username):esc(u.phone||'')}</div></div><div style="text-align:right"><b>${money(u.total_spent_uzs||0)}</b><div class="muted">${num(u.delivered_orders)} yetkazilgan</div></div></div></div>`).join(''):'<div class="empty">Mijozlar topilmadi</div>'}</div>`;c.innerHTML=h}
window.setAnalyticsPeriod=async function(p){analyticsPeriod=p;await renderAnalytics()};
async function loadCustomers(search=''){const r=await acall('customers',{search,limit:150}).catch(()=>null);if(!r?.ok)throw new Error(r?.error||'crm_load_failed');crmRows=r.customers||[];return crmRows}
function customerCards(rows){if(!rows.length)return'<div class="empty">Mijoz topilmadi</div>';return rows.map(u=>`<div class="crmCard"><div class="anaHead"><div><b>${esc(u.customer_name||'Noma’lum')}</b><div class="crmMeta">${u.username?'@'+esc(u.username)+'<br>':''}${esc(u.phone||'Telefon yo‘q')}<br>ID: ${esc(u.telegram_user_id)}</div></div><div style="text-align:right"><b>${money(u.total_spent_uzs||0)}</b><div class="muted">Jami xarid</div></div></div><div class="crmStats"><div class="crmMini"><b>${num(u.total_orders)}</b><span>Buyurtma</span></div><div class="crmMini"><b>${num(u.delivered_orders)}</b><span>Yetkazildi</span></div><div class="crmMini"><b>${num(u.cancelled_orders)}</b><span>Bekor</span></div></div><button class="crmDetail" onclick="openCustomerDetail('${u.telegram_user_id}')">Mijoz kartasi</button></div>`).join('')}
async function renderCrm(search=''){analyticsMode=false;crmMode=true;const c=document.querySelector('#content');if(!c)return;c.innerHTML=`<div class="crmSearch"><div class="toolbar"><div><b>Mijozlar CRM</b><div class="muted">Ism, telefon, @username yoki ID bo‘yicha qidiring</div></div><button onclick="renderCrm(document.querySelector('#crmQ')?.value||'')">↻</button></div><input id="crmQ" placeholder="Mijoz qidirish..." value="${esc(search)}" oninput="crmSearchChanged(this.value)"></div><div id="crmList"><div class="empty">Mijozlar yuklanmoqda...</div></div>`;try{const rows=await loadCustomers(search);const el=document.querySelector('#crmList');if(el)el.innerHTML=customerCards(rows)}catch(e){const el=document.querySelector('#crmList');if(el)el.innerHTML='<div class="empty">CRM yuklanmadi: '+esc(e.message||e)+'</div>'}}
window.crmSearchChanged=function(v){clearTimeout(crmTimer);crmTimer=setTimeout(()=>renderCrm(String(v||'').trim()),350)};
window.openCustomerDetail=function(id){const u=crmRows.find(x=>String(x.telegram_user_id)===String(id));if(!u)return;document.querySelector('#form').innerHTML=`<h3>👤 Mijoz kartasi</h3><div class="crmCard"><b style="font-size:18px">${esc(u.customer_name||'Noma’lum')}</b><div class="crmMeta">${u.username?'@'+esc(u.username)+'<br>':''}📞 ${esc(u.phone||'Telefon yo‘q')}<br>Telegram ID: ${esc(u.telegram_user_id)}<br>Birinchi buyurtma: ${esc(fmtDate(u.first_order_at))}<br>Oxirgi buyurtma: ${esc(fmtDate(u.last_order_at))}<br>Oxirgi status: ${esc(sname[u.last_status]||u.last_status||'-')}</div><div class="crmStats"><div class="crmMini"><b>${num(u.total_orders)}</b><span>Buyurtma</span></div><div class="crmMini"><b>${num(u.delivered_orders)}</b><span>Yetkazildi</span></div><div class="crmMini"><b>${num(u.cancelled_orders)}</b><span>Bekor</span></div></div><div class="anaCard" style="margin-top:9px"><div class="anaValue">${money(u.total_spent_uzs||0)}</div><div class="anaLabel">Jami yetkazilgan xarid</div></div></div><button style="width:100%" onclick="document.querySelector('#modal').style.display='none'">Yopish</button>`;document.querySelector('#modal').style.display='flex'};
window.openCrmTab=async function(){clearTabs();const b=document.querySelector('[data-tab="crm"]');b?.classList.add('active');await renderCrm('')};
async function initAnalytics(){addAnalyticsStyles();const tabs=document.querySelector('.tabs');if(!tabs||document.querySelector('[data-tab="analytics"]'))return;const orders=tabs.querySelector('[data-tab="orders"]');const a=document.createElement('button');a.dataset.tab='analytics';a.textContent='Analitika';a.onclick=async()=>{clearTabs();a.classList.add('active');await renderAnalytics()};const c=document.createElement('button');c.dataset.tab='crm';c.textContent='Mijozlar';c.onclick=async()=>{clearTabs();c.classList.add('active');await renderCrm('')};if(orders?.nextSibling){tabs.insertBefore(c,orders.nextSibling);tabs.insertBefore(a,c)}else{tabs.appendChild(a);tabs.appendChild(c)}document.querySelectorAll('.tabs button:not([data-tab="analytics"]):not([data-tab="crm"])').forEach(x=>x.addEventListener('click',()=>{analyticsMode=false;crmMode=false}))}
setTimeout(initAnalytics,260);
})();