(()=>{
const PROMO_API='https://tgcmevhuxwzcmeseysax.supabase.co/functions/v1/bbq-promo-admin-api';
let promoMode=false,promos=[];
const pcall=async(action,extra={})=>{const r=await fetch(PROMO_API,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,initData,...extra})});return r.json()};
function styles(){if(document.querySelector('#promoAdminStyle'))return;const s=document.createElement('style');s.id='promoAdminStyle';s.textContent='.promoCard{background:#fff;border-radius:17px;padding:13px;margin:9px 0;box-shadow:0 3px 14px #0000000c}.promoHead{display:flex;justify-content:space-between;gap:9px}.promoCode{font-size:18px;font-weight:950;letter-spacing:.5px}.promoMeta{font-size:11px;color:#777;line-height:1.55;margin-top:7px}.promoValue{font-weight:950;color:#c84f00}.promoBtns{display:flex;gap:6px;margin-top:10px}.promoBtns button{flex:1}.promoOff{background:#fde7e7;color:#c62828}.promoOn{background:#e5f6e9;color:#16813c}.promoUsed{font-size:10px;background:#f1f1f1;border-radius:999px;padding:5px 7px}.promoFormHelp{font-size:10.5px;color:#777;margin:-5px 0 9px}.promoGrid{display:grid;grid-template-columns:1fr 1fr;gap:8px}';document.head.appendChild(s)}
function addTab(){if(document.querySelector('[data-tab="promos"]'))return;const tabs=document.querySelector('.tabs');if(!tabs)return;const b=document.createElement('button');b.dataset.tab='promos';b.textContent='Promolar';b.onclick=async()=>{document.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');promoMode=true;await renderPromos()};tabs.appendChild(b);document.querySelectorAll('.tabs button:not([data-tab="promos"])').forEach(x=>x.addEventListener('click',()=>promoMode=false))}
async function renderPromos(){const c=document.querySelector('#content');c.innerHTML='<div class="empty">Promo-kodlar yuklanmoqda...</div>';const r=await pcall('list');if(!r.ok){c.innerHTML='<div class="empty">Xatolik: '+esc(r.error)+'</div>';return}promos=r.promos||[];let h=`<div class="toolbar"><div><b>Promo-kodlar</b><div class="muted">Chegirma va foydalanish limitlari</div></div><button class="primary" onclick="openPromoForm()">+ Promo</button></div>`;h+=promos.map(x=>{const val=x.discount_type==='percent'?`${x.discount_value}%`:money(x.discount_value),min=x.min_order_uzs?`Min: ${money(x.min_order_uzs)}`:'Minimum yo‘q',end=x.ends_at?`Tugaydi: ${new Date(x.ends_at).toLocaleString()}`:'Muddatsiz',limit=x.max_uses?`${x.used_count||0}/${x.max_uses} ishlatilgan`:`${x.used_count||0} marta ishlatilgan`;return `<div class="promoCard"><div class="promoHead"><div><div class="promoCode">${esc(x.code)}</div><div class="promoValue">${val} chegirma</div></div><span class="promoUsed">${esc(limit)}</span></div><div class="promoMeta">${min}<br>${end}<br>Har mijoz: ${x.max_uses_per_user} marta · ${x.is_active?'Faol':'O‘chiq'}</div><div class="promoBtns"><button onclick="openPromoForm('${x.id}')">✏️ Tahrirlash</button><button class="${x.is_active?'promoOff':'promoOn'}" onclick="togglePromo('${x.id}',${!x.is_active})">${x.is_active?'⏸ O‘chirish':'▶️ Yoqish'}</button></div></div>`}).join('')||'<div class="empty">Hali promo-kod yo‘q.</div>';c.innerHTML=h}
function dt(v){if(!v)return'';const d=new Date(v),z=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${z(d.getMonth()+1)}-${z(d.getDate())}T${z(d.getHours())}:${z(d.getMinutes())}`}
window.openPromoForm=function(id=''){const x=id?promos.find(p=>p.id===id)||{}:{};document.querySelector('#form').innerHTML=`<h3>${id?'Promo-kodni tahrirlash':'Yangi promo-kod'}</h3><label>Promo-kod</label><input id="pcCode" maxlength="30" value="${esc(x.code||'')}" placeholder="BBQ10"><div class="promoFormHelp">3–30 belgi: A-Z, 0-9, _ yoki -</div><label>Chegirma turi</label><select id="pcType"><option value="percent" ${x.discount_type!=='fixed'?'selected':''}>Foiz (%)</option><option value="fixed" ${x.discount_type==='fixed'?'selected':''}>Aniq summa (so‘m)</option></select><div class="promoGrid"><div><label>Chegirma qiymati</label><input id="pcValue" type="number" min="1" value="${x.discount_value||10}"></div><div><label>Minimal buyurtma</label><input id="pcMin" type="number" min="0" value="${x.min_order_uzs||0}"></div></div><label>Maksimal chegirma (foiz uchun)</label><input id="pcMaxDiscount" type="number" min="0" value="${x.max_discount_uzs||''}" placeholder="Bo‘sh = limitsiz"><div class="promoGrid"><div><label>Boshlanishi</label><input id="pcStart" type="datetime-local" value="${dt(x.starts_at)}"></div><div><label>Tugashi</label><input id="pcEnd" type="datetime-local" value="${dt(x.ends_at)}"></div></div><div class="promoGrid"><div><label>Umumiy foydalanish limiti</label><input id="pcMaxUses" type="number" min="1" value="${x.max_uses||''}" placeholder="Bo‘sh = limitsiz"></div><div><label>Har bir mijoz uchun</label><input id="pcPerUser" type="number" min="1" value="${x.max_uses_per_user||1}"></div></div><label>Holati</label><select id="pcActive"><option value="true" ${x.is_active!==false?'selected':''}>Faol</option><option value="false" ${x.is_active===false?'selected':''}>O‘chiq</option></select><div class="row"><button onclick="closeM()">Bekor</button><button class="primary" onclick="savePromo('${id}')">Saqlash</button></div>`;document.querySelector('#modal').style.display='flex'};
window.savePromo=async function(id=''){const code=document.querySelector('#pcCode').value.trim().toUpperCase(),type=document.querySelector('#pcType').value,row={id:id||undefined,code,discount_type:type,discount_value:+document.querySelector('#pcValue').value,min_order_uzs:+document.querySelector('#pcMin').value,max_discount_uzs:document.querySelector('#pcMaxDiscount').value||null,starts_at:document.querySelector('#pcStart').value||null,ends_at:document.querySelector('#pcEnd').value||null,max_uses:document.querySelector('#pcMaxUses').value||null,max_uses_per_user:+document.querySelector('#pcPerUser').value,is_active:document.querySelector('#pcActive').value==='true'};if(!/^[A-Z0-9_-]{3,30}$/.test(code)){alert('Promo-kod formati noto‘g‘ri');return}const r=await pcall('save',{row});if(!r.ok){alert(r.error);return}document.querySelector('#modal').style.display='none';tg?.HapticFeedback?.notificationOccurred('success');await renderPromos()};
window.togglePromo=async function(id,is_active){const r=await pcall('toggle',{id,is_active});if(!r.ok){alert(r.error);return}await renderPromos()};
styles();addTab();
const obs=new MutationObserver(()=>{addTab();if(promoMode&&document.querySelector('#content')&&!document.querySelector('.promoCard')&&!document.querySelector('#content .toolbar'))renderPromos()});obs.observe(document.documentElement,{childList:true,subtree:true});
})();